server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: ${IDENTITY_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/identity/**

        - id: profile_service
          uri: ${PROFILE_SERVICE_URL:http://localhost:8091}
          predicates:
            - Path=/profile/**

        - id: notification_service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/notification/**

        - id: post_service
          uri: ${POST_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/post/**

        - id: file_service
          uri: ${FILE_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/file/**

        - id: book_service
          uri: ${BOOK_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/books/**

        - id: chat_service
          uri: ${CHAT_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/chat/**