server:
  port: 8083
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/post-service?authSource=admin}

app:
  services:
    profile:
      url: ${APP_SERVICES_PROFILE_URL:http://localhost:8091/profile}