server:
  port: 8085
  servlet:
    context-path: /books

spring:
  application:
    name: book-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/book-service?authSource=admin}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  services:
    profile:
      url: ${APP_SERVICES_PROFILE_URL:http://localhost:8091/profile}
  base-url: ${APP_BASE_URL:http://localhost:8085}