server:
  port: 8085
  servlet:
    context-path: /books

spring:
  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/book-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  services:
    profile:
      url: http://localhost:8081/profile