server:
  port: 8086
  servlet:
    context-path: /chat
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/chat-service?authSource=admin}
      auto-index-creation: true
app:
  services:
    profile:
      url: ${APP_SERVICES_PROFILE_URL:http://localhost:8091/profile}
